-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) AS SALES FROM BOOK A
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
    WHERE YEAR(C.SALES_DATE) = '2022' AND MONTH(C.SALES_DATE) = '01'
    GROUP BY 2, 3
    ORDER BY 1, 3 DESC;