-- 코드를 작성해주세요
# parent_id를 그룹화 해서 갯수를 센다?
WITH PARENT_CNT AS(
    SELECT PARENT_ID, COUNT(*) AS CNT FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
)

# SELECT A.ID AS ID, IFNULL(B.CNT,0) AS CHILD_COUNT
#     FROM ECOLI_DATA A 
#     LEFT JOIN PARENT_CNT B ON A.PARENT_ID = B.PARENT_ID

# SELECT * FROM ECOLI_DATA
# 1->1 2->2 4->1
SELECT A.ID AS ID, IFNULL(B.CNT, 0) AS CHILD_COUNT 
    FROM ECOLI_DATA A 
    LEFT JOIN PARENT_CNT B ON A.ID = B.PARENT_ID