-- 코드를 작성해주세요
WITH SUBQUERY AS (
    SELECT ID, SIZE_OF_COLONY, RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS NUM
    , COUNT(*) OVER() AS TOTAL_COUNT 
        FROM ECOLI_DATA
)

SELECT ID, CASE
    WHEN NUM <= TOTAL_COUNT / 4 THEN 'CRITICAL'
    WHEN NUM <= TOTAL_COUNT / 2 THEN 'HIGH'
    WHEN NUM <= TOTAL_COUNT * 3 / 4 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
    FROM SUBQUERY
    ORDER BY 1;