-- 코드를 입력하세요
WITH NONE_SEX AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)

# SELECT ANIMAL_ID, ANIMAL_TYPE, NAME, SEX_UPON_INTAKE FROM ANIMAL_INS
#     WHERE SEX_UPON_INTAKE LIKE '%Intact%'

SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME FROM ANIMAL_OUTS A
    JOIN NONE_SEX B ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE A.SEX_UPON_OUTCOME LIKE '%Neutered%' OR A.SEX_UPON_OUTCOME LIKE '%Spayed%'
    ORDER BY 1