# -- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1), 1) AS AVERAGE_DURATION FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    GROUP BY CAR_ID
    HAVING AVERAGE_DURATION >= 7
    ORDER BY 2 DESC, CAR_ID DESC;
    
# SELECT CAR_ID, START_DATE, END_DATE, DATEDIFF(END_DATE, START_DATE) AS '차이' FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE CAR_ID = 26;
-- 3, 4, 0, 100 -> 107/4 =