-- 코드를 입력하세요
-- 하나의 ID가 여러 번의 대여를 했을 경우에 대한 고려가 필요
SELECT CAR_ID, CASE WHEN SUM(CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN 1 ELSE 0 END) = 1
                    THEN '대여중' ELSE '대여 가능'
                    END AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY 1
    ORDER BY 1 DESC;
  
  
  
  
  
  
  
  
  
  
  
# SELECT CAR_ID, CASE WHEN SUM(
#     CASE WHEN START_DATE <= '2022-10-16' 
#     AND END_DATE >= '2022-10-16' 
#     THEN 1 ELSE 0 END) = 0 
#     THEN '대여 가능' ELSE '대여중' END AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY CAR_ID DESC;