-- 코드를 입력하세요
WITH FH AS (
    SELECT A.SHIPMENT_ID, A.FLAVOR, A.TOTAL_ORDER FROM FIRST_HALF A
    JOIN JULY B ON A.SHIPMENT_ID = B.SHIPMENT_ID
)

SELECT J.FLAVOR FROM JULY J
    JOIN FIRST_HALF F ON J.FLAVOR = F.FLAVOR
    JOIN FH H ON J.FLAVOR = H.FLAVOR
    GROUP BY J.FLAVOR
    ORDER BY SUM(J.TOTAL_ORDER) + H.TOTAL_ORDER DESC
    LIMIT 3;