-- 코드를 작성해주세요
# 부모의 GENOTYPE 과 자식의 GENOTYPE 을 비교
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE 
    FROM ECOLI_DATA A
    JOIN ECOLI_DATA B ON A.PARENT_ID = B.ID
    WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
    ORDER BY 1;