-- 코드를 작성해주세요
WITH MaxsizeByYear as (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
# SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA
#     GROUP BY DIFFERENTIATION_DATE
#     HAVING YEAR(DIFFERENTIATION_DATE);
    
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MSY.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
    FROM ECOLI_DATA B
    JOIN MaxSizeByYear MSY ON YEAR(B.DIFFERENTIATION_DATE) = MSY.YEAR
    ORDER BY 1, 2;