-- 코드를 작성해주세요
WITH SUBQUERY AS(
    SELECT COUNT(*) AS FISH_CNT 
    FROM FISH_INFO A
    JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
    WHERE B.FISH_NAME = 'BASS' OR B.FISH_NAME = 'SNAPPER'
    GROUP BY A.FISH_TYPE
)

SELECT SUM(FISH_CNT) AS FISH_COUNT
    FROM SUBQUERY;
    