-- 코드를 작성해주세요
SELECT SUM(B.SCORE) AS SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
    WHERE B.EMP_NO = (SELECT EMP_NO FROM HR_GRADE
        GROUP BY EMP_NO, YEAR
        ORDER BY SUM(SCORE) DESC LIMIT 1)
    GROUP BY A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL;
        
        
# SELECT EMP_NO, YEAR, SUM(SCORE) FROM HR_GRADE
#         GROUP BY EMP_NO, YEAR
#         ORDER BY  DESC LIMIT 1