-- 코드를 입력하세요
SELECT A.CATEGORY AS CATEGORY, SUM(B.SALES) AS TOTAL_SALES FROM BOOK A
    JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
    WHERE YEAR(B.SALES_DATE) = '2022' AND MONTH(B.SALES_DATE) = '01'
    GROUP BY 1
    ORDER BY 1;