-- 코드를 입력하세요
SELECT A.category as CATEGORY, sum(b.sales) as TOTAL_SALES
    FROM BOOK A JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
    WHERE YEAR(b.SALES_DATE) = '2022' AND MONTH(B.SALES_DATE) = '01'
    GROUP BY CATEGORY
    ORDER BY CATEGORY;